AWSTemplateFormatVersion: 2010-09-09
Description: Creation of S3 buckets
Resources:
  GitHubCFNDeployDemo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: github-cfn-demo-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionExpirationInDays
            Status: Enabled
            NoncurrentVersionExpirationInDays: 1
            ExpiredObjectDeleteMarker: true              
